blank_issues_enabled: false
contact_links:
<<<<<<< HEAD
  - name: Motion User Questions
    url: https://github.com/Motion-Project/motion/discussions
    about: Please ask and answer questions here.
  - name: Motion Enhancements
    url: https://github.com/Motion-Project/motion/discussions
=======
  - name: MotionPlus User Questions
    url: https://github.com/Motion-Project/motionplus/discussions
    about: Please ask and answer questions here.
  - name: MotionPlus Enhancements
    url: https://github.com/Motion-Project/motionplus/discussions
>>>>>>> plus/upstream__May25
    about: Please use the discussions page and tag as an enhancement request.
